#!/bin/bash
lsb_dist_id="$(lsb_release -si)"  
product_model="$(sed -e 's/^\s*//g' -e 's/\s*$//g' "/sys/devices/virtual/dmi/id/product_name" | tr ' ,/-' '_')"
chassis="$(hostnamectl | awk 'FNR==3 {print $2}')"
codename="$(lsb_release -c | awk '{print $2}')"
de="$(ps axf | grep -Po "env \.*[A-Z]+" | awk '{print $2}' | sort -u)"
ecsys="$(cat /boot/config-$(uname -r) | grep CONFIG_ACPI_EC)"

#--------------------------------------

update-pciids

#Install Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#Add User to Audio
echo "Adding $USER to Audio & Input"
sed 's/#EXTRA_GROUPS.*/EXTRA_GROUPS="audio input clevo-keyboard adm"/' -i /etc/adduser.conf
sed 's/#ADD_EXTRA_GROUPS=1/ADD_EXTRA_GROUPS=1/g' -i /etc/adduser.conf

#GRUB
echo "Updating Grub"
sleep 3

case "$product_model" in
#    N130BU|N131BU|N130WU|N131WU|N13xWU|N13xZU|N140BU|N141BU|N140WU|N141WU|N14xWU|N140ZU|N141ZU|N14xZU|N13_N140ZU|N140ZU|N141ZU|N140CU|N141CU|N14xCU|N150ZU|N151ZU|N15xZU|N150CU|N151CU|N15xCU|N240GU|N240WU|N24_25GU|NL40GU|NL41GU|NL4xGU|NL40_50GU|NL40CU|NL41CU|NL4xCU|NL40_50CU)
#    sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#    sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop intel_idle.max_cstate=1"' /etc/default/grub
#    ;;
#    NL50RU|NL51RU|NL5xRU|NL4x_NL5xRU)
#    echo "Nyx 15 AMD ($chassis)"
#    sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#    sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop iommu=off"' /etc/default/grub
#    ;;
#    To_be_filled_by_O.E.M.) #JUVE
#    if [ "$(dmidecode -s processor-version | grep -Po 'N4000')" == 'N4000' ]; then
#	echo " Juve v1 ($chassis)";
#	sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub;
#    	sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop intel_idle.max_cstate=1"' /etc/default/grub;
#    elif [ "$(dmidecode -s processor-version | grep -Po 'N3350')" == 'N3350' ]; then
#	echo " Juve v2 ($chassis)";
#	sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub;
#   	sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop intel_idle.max_cstate=1"' /etc/default/grub;
#    fi
#    ;;
    NUC10i3FNH|NUC10i5FNH|NUC10i7FNH|NUC10i3FNK|NUC10i5FNK|NUC10i7FNK)
    echo "Olympia 8th Gen ($chassis)"
    if 
	grep 'hw:0,0' /etc/pulse/default.pa
	then 
	echo "Olympia (10th Gen) headphone jack drivers already exist";
	else
	echo 'load-module module-alsa-sink device=hw:0,0' >> /etc/pulse/default.pa;
	echo "Olympia (10th Gen) headphone jack drivers installed";
    fi
    ;;
#   To_Be_Filled_By_O.E.M.)
#   echo "Brutus ($chassis)"
#    sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#    sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash iommu=pt nvme_core.default_ps_max_latency_us=0"' /etc/default/grub
#    ;;
#    NP50D5|NP5x_NP7xHH_HJ_HK|NP5x_NP6x_NP7xHP|NP5x_NP6x_NP7xPNP|PD5x_7xPNP_PNR_PNN_PNT|PD5x_7xPNP_PNN_PNT|NH5xVR|PE60RNE_RND_RNC|NP5x_NP6x_NP7xRNJ_RNH|NP5x_NP6x_NP7xRNA_RNB)
#    sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#    sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop modprobe.blacklist=psmouse"' /etc/default/grub
#    ;;
#    NV4XMZ|NV4XMB_ME_MZ|NV4XMJ_MK_MH|NV4xPZ|NS50MU|NS50_70MU|NL40LU|NL41LU|NL4xLU|NL4x_NL5xLU|NL50NU|NL51NU|NL5xNU|NL4x_NL5xNU|NL4x_NLxNU|NJ5x_NJ7xLU|NJ5x_NJ7xCU|NJ50_70CU|PCX0DX|PCx0Dx|PC5x_7xHP_HR_HS|NP50DE_DB|NH5x_7xDPx|NLx0MU|NJx0MU|NS5x_NS7xPU|NS5x_NS7xAU|NLxxPUx|NJx0PU|X370SNx)
#    sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#    sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop"' /etc/default/grub
#    ;;
    *)
    echo "Model not recognized ($product_model)"
    ;;
esac

sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub;
sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash $(/usr/share/junocomp/juno-grub)"' /etc/default/grub
update-grub

echo "GRUB has been updated"

# Enable Systemd
systemctl enable thermald
systemctl enable irqbalance

# Disable Power Profiles Rules for Desktops
case "$product_model" in
    NUC10i3FNH|NUC10i5FNH|NUC10i7FNH|NUC10i3FNK|NUC10i5FNK|NUC10i7FNK|To_Be_Filled_By_O.E.M.|BQM5|TB_4000|SYSTEM_PRODUCT_NAME)
    if [ -f /etc/udev/rules.d/power-profiles.rules ]; then
    rm /etc/udev/rules.d/power-profiles.rules;
    fi
    ;;
esac

# Enable Juno PP
case "$product_model" in
    NUC10i3FNH|NUC10i5FNH|NUC10i7FNH|NUC10i3FNK|NUC10i5FNK|NUC10i7FNK|To_Be_Filled_By_O.E.M.|BQM5|TB_4000|SYSTEM_PRODUCT_NAME)
    systemctl disable juno-pp.service
    ;;
    *)
    systemctl enable juno-pp.service
    ;;
esac

#Rules for ACPI
case "$product_model" in
    NL50RU|NL51RU|NL5xRU|NL4x_NL5xRU|NL5xNU|NL4x_NLxNU|NH5xVR)
    if [ -f /etc/udev/rules.d/juno-cpufreq.rules ]; then
    rm /etc/udev/rules.d/juno-cpufreq.rules;
    else
    ln -s /usr/share/nv41/udev/juno-cpufreq.rules /etc/udev/rules.d/juno-cpufreq.rules
    fi
    ;;
esac

#FIX AUDIO
case "$product_model" in
    PE60RNE_RND_RNC)
    if [ -f /etc/modprobe.d/juno-audio-fix.conf ]; then
       rm /etc/modprobe.d/juno-audio-fix.conf;
       cp /usr/share/junocomp/juno-audio-fix.conf /etc/modprobe.d;
       else
       cp /usr/share/junocomp/juno-audio-fix.conf /etc/modprobe.d;
    fi
    ;;
esac

#Fix i2c_hid after suspend
case "$product_model" in
    NP5x_NP6x_NP7xHP|NP5x_NP7xHH_HJ_HK)
    if [ -f /usr/lib/systemd/system-sleep/restore-i2c-hid ]; then
       rm /usr/lib/systemd/system-sleep/restore-i2c-hid;
       cp /usr/share/junocomp/restore-i2c-hid /usr/lib/systemd/system-sleep/;
       chmod +x /usr/lib/systemd/system-sleep/restore-i2c-hid;
       else
       cp /usr/share/junocomp/restore-i2c-hid /usr/lib/systemd/system-sleep/;
       chmod +x /usr/lib/systemd/system-sleep/restore-i2c-hid;
    fi
    ;;
esac

#MSR Module
if grep -q 'msr' "/etc/modules";
   then
     echo 'msr module exist';
   else
     echo "Adding msr to modules"
     echo msr >> /etc/modules;
     modprobe msr;
fi

#DISABLE APPORT
#if grep -q "enabled=1" "/etc/default/apport" ; then

#        echo 'Disabling Apport';
#        sed -i 's/enabled=1/enabled=0/' /etc/default/apport;

#        else echo 'Apport is already disabled';
#fi


#AMDGPU Acceleration
case "$product_model" in
    To_Be_Filled_By_O.E.M.|TB_4000)
if 
	grep 'TearFree' /usr/share/X11/xorg.conf.d/10-amdgpu.conf;
then 
	echo "TearFree already exist in 10-amdgpu.conf";
else
	sed -i '/\EndSection/i Option "TearFree" "true"' /usr/share/X11/xorg.conf.d/10-amdgpu.conf;
fi

if 
	grep 'DRI' /usr/share/X11/xorg.conf.d/10-amdgpu.conf;
then 
	echo "DRI3 already exist in 10-amdgpu.conf";
else
	sed -i '/\EndSection/i Option "DRI" "3"' /usr/share/X11/xorg.conf.d/10-amdgpu.conf;
fi
;;
esac

#Enable LM92
if ! grep -Fxq 'lm92' '/etc/modules' ; then
   echo 'Adding lm92';
   echo 'lm92' >> /etc/modules;
   modprobe lm92;

   else echo 'lm92 already enabled';
fi

#Enable ec_sys
if ! grep -Fxq 'ec_sys' '/etc/modules' ; then
   echo 'Adding ec_sys';
   echo 'ec_sys' >> /etc/modules;
   modprobe ec_sys;

   else echo 'ec_sys already in /etc/modules';
fi

# Install Brasero icons for Juno Fan Indicator
cp /usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-* /usr/share/icons/hicolor/scalable/status/

# Update Schemas
glib-compile-schemas /usr/share/glib-2.0/schemas/