#!/bin/bash
product_model="$(sed -e 's/^\s*//g' -e 's/\s*$//g' "/sys/devices/virtual/dmi/id/product_name" | tr ' ,/-' '_')"
chassis="$(hostnamectl | awk 'FNR==3 {print $2}')"

#--------------------------------------

#Install Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

case "$product_model" in
    NUC10i3FNH|NUC10i5FNH|NUC10i7FNH|NUC10i3FNK|NUC10i5FNK|NUC10i7FNK)
    echo "Olympia 8th Gen ($chassis)"
    if
	grep 'hw:0,0' /etc/pulse/default.pa
	then
	echo "Olympia (10th Gen) headphone jack drivers already exist";
	else
	echo 'load-module module-alsa-sink device=hw:0,0' >> /etc/pulse/default.pa;
	echo "Olympia (10th Gen) headphone jack drivers installed";
    fi
    ;;
esac

# Enable Systemd
systemctl enable thermald

#Rules for ACPI
case "$product_model" in
    NL50RU|NL51RU|NL5xRU|NL4x_NL5xRU|NL5xNU|NL4x_NLxNU|NH5xVR)
    if [ -f /etc/udev/rules.d/juno-cpufreq.rules ]; then
    rm /etc/udev/rules.d/juno-cpufreq.rules;
    else
    ln -s /usr/share/nv41/udev/juno-cpufreq.rules /etc/udev/rules.d/juno-cpufreq.rules
    fi
    ;;
esac

#FIX AUDIO
case "$product_model" in
    PE60RNE_RND_RNC)
    if [ -f /etc/modprobe.d/juno-audio-fix.conf ]; then
       rm /etc/modprobe.d/juno-audio-fix.conf;
       cp /usr/share/junocomp/juno-audio-fix.conf /etc/modprobe.d;
       else
       cp /usr/share/junocomp/juno-audio-fix.conf /etc/modprobe.d;
    fi
    ;;
esac

#Fix i2c_hid after suspend
case "$product_model" in
    NP5x_NP6x_NP7xHP|NP5x_NP7xHH_HJ_HK)
    if [ -f /usr/lib/systemd/system-sleep/restore-i2c-hid ]; then
       rm /usr/lib/systemd/system-sleep/restore-i2c-hid;
       cp /usr/share/junocomp/restore-i2c-hid /usr/lib/systemd/system-sleep/;
       chmod +x /usr/lib/systemd/system-sleep/restore-i2c-hid;
       else
       cp /usr/share/junocomp/restore-i2c-hid /usr/lib/systemd/system-sleep/;
       chmod +x /usr/lib/systemd/system-sleep/restore-i2c-hid;
    fi
    ;;
esac

# Enable touchpad buttons NJ70AU
case "$product_model" in
    NJx0AU|NJ7xPU|NJ7xMU)
    if [ -f /usr/share/X11/xorg.conf.d/60-nj70au-touchpad.conf ]; then
    rm /usr/share/X11/xorg.conf.d/60-nj70au-touchpad.conf;
    cp /usr/share/junocomp/60-nj70au-touchpad.conf /usr/share/X11/xorg.conf.d;
    else
    cp /usr/share/junocomp/60-nj70au-touchpad.conf /usr/share/X11/xorg.conf.d;
    fi
    ;;
esac

# Update Schemas
glib-compile-schemas /usr/share/glib-2.0/schemas/
