#!/bin/bash

# REMOVE RESTORE AUDIO FOR NJ70CU
if [ -f /usr/lib/systemd/system-sleep/restart-audio ]; then
   rm /usr/lib/systemd/system-sleep/restart-audio;
fi

if [ -f /usr/lib/systemd/system-sleep/99-restart-audio ]; then
   rm /usr/lib/systemd/system-sleep/99-restart-audio;
fi

if [ -f /etc/udev/rules.d/juno-cpufreq.rules ]; then
   rm /etc/udev/rules.d/juno-cpufreq.rules;
fi

# Remove juno-grub line and use it from the juno-grub package instead
sed -r -i '/^GRUB_CMDLINE_LINUX_DEFAULT/ s/(usr|share|junocomp|juno-grub|[/]|[()])|[$]//g' /etc/default/grub