#!/bin/bash

# REMOVE TLP CONF
if [ -f /etc/tlp.d/juno-tlp.conf ]; then
   rm /etc/tlp.d/juno-tlp.conf;
fi

if [ -f /etc/udev/rules.d/juno-cpufreq.rules ]; then
   rm /etc/udev/rules.d/juno-cpufreq.rules;
fi

#Remove audio fix
if [ -f /etc/modprobe.d/juno-audio-fix.conf ]; then
   rm /etc/modprobe.d/juno-audio-fix.conf;
fi

add-apt-repository ppa:libreoffice/ppa --remove -y

# Remove extensions
if [ -d /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com ];then
   rm -Rf /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com;
fi

if [ -d /usr/share/gnome-shell/extensions/lockkeys@vaina.lt ]; then
   rm -Rf /usr/share/gnome-shell/extensions/lockkeys@vaina.lt;
fi

if [ -d /usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net ]; then
   rm -Rf /usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net;
fi

if [ -d /usr/share/gnome-shell/extensions/freq-boost-switch@metal03326 ]; then
   rm -Rf /usr/share/gnome-shell/extensions/freq-boost-switch@metal03326;
fi

# Remove Ubuntu Schema
if [ -f /usr/share/glib-2.0/schemas/10_juno-ubuntu-settings.gschema.override ]; then
   rm /usr/share/glib-2.0/schemas/10_juno-ubuntu-settings.gschema.override;
fi
