#!/bin/bash
# Juno Computers

INTEL="/sys/devices/system/cpu/intel_pstate/no_turbo"
ACPI="/sys/devices/system/cpu/cpufreq/boost"
FREQ="$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver | sort -u)"

case "$FREQ" in
    acpi-cpufreq)
    echo "0" | sudo tee $ACPI;
    echo "Turbo Off"
    ;;
    intel_pstate)
    echo "1" | sudo tee $INTEL;
    echo "Turbo Off";
    ;;
esac

